name: 'SecurityUse Scan'
description: 'Scan dependencies and IaC for security vulnerabilities'
author: 'SecurityUse'

branding:
  icon: 'shield'
  color: 'green'

inputs:
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  scan-type:
    description: 'Type of scan: deps, iac, or all'
    required: false
    default: 'all'
  fail-on:
    description: 'Minimum severity to fail on: critical, high, medium, low'
    required: false
    default: 'high'
  format:
    description: 'Output format: table, json, sarif'
    required: false
    default: 'sarif'
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'
  comment-on-pr:
    description: 'Add scan summary as PR comment'
    required: false
    default: 'true'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

outputs:
  vulnerabilities:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.scan.outputs.vulnerabilities }}
  iac-findings:
    description: 'Number of IaC findings'
    value: ${{ steps.scan.outputs.iac_findings }}
  sarif-file:
    description: 'Path to SARIF output file'
    value: ${{ steps.scan.outputs.sarif_file }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install SecurityUse
      shell: bash
      run: pip install security-use

    - name: Run Security Scan
      id: scan
      shell: bash
      env:
        SCAN_TYPE: ${{ inputs.scan-type }}
        SCAN_PATH: ${{ inputs.path }}
        FAIL_ON: ${{ inputs.fail-on }}
        OUTPUT_FORMAT: ${{ inputs.format }}
      run: |
        set +e

        SARIF_FILE="security-use-results.sarif"

        if [ "$SCAN_TYPE" = "deps" ]; then
          security-use scan deps "$SCAN_PATH" --format sarif --severity "$FAIL_ON" > "$SARIF_FILE" 2>&1
        elif [ "$SCAN_TYPE" = "iac" ]; then
          security-use scan iac "$SCAN_PATH" --format sarif --severity "$FAIL_ON" > "$SARIF_FILE" 2>&1
        else
          security-use scan all "$SCAN_PATH" --format sarif --severity "$FAIL_ON" > "$SARIF_FILE" 2>&1
        fi

        EXIT_CODE=$?

        # Parse results for outputs
        if [ -f "$SARIF_FILE" ]; then
          VULN_COUNT=$(grep -c '"ruleId"' "$SARIF_FILE" 2>/dev/null || echo "0")
        else
          VULN_COUNT=0
        fi

        echo "vulnerabilities=$VULN_COUNT" >> $GITHUB_OUTPUT
        echo "iac_findings=$VULN_COUNT" >> $GITHUB_OUTPUT
        echo "sarif_file=$SARIF_FILE" >> $GITHUB_OUTPUT

        # Also output in table format for logs
        if [ "$OUTPUT_FORMAT" = "table" ] || [ "$OUTPUT_FORMAT" = "sarif" ]; then
          echo "## Security Scan Results"
          security-use scan $SCAN_TYPE "$SCAN_PATH" --format table --severity "$FAIL_ON" || true
        fi

        exit $EXIT_CODE

    - name: Upload SARIF to GitHub
      if: inputs.upload-sarif == 'true' && always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif_file }}
        category: security-use

    - name: Comment on PR
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const vulns = '${{ steps.scan.outputs.vulnerabilities }}';
          const findings = '${{ steps.scan.outputs.iac_findings }}';

          let body = '## 🔒 SecurityUse Scan Results\n\n';

          if (vulns === '0' && findings === '0') {
            body += '✅ No security issues found!\n';
          } else {
            body += `Found **${vulns}** security issue(s).\n\n`;
            body += 'See the Security tab for details.\n';
          }

          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: body
          });
